version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.bsite.net\MSSQL2016;Database=webmusicapp_;User Id=webmusicapp_;Password=password_123;TrustServerCertificate=true;
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=password_123"
      - "ACCEPT_EULA=Y"
    container_name: mssql2
    ports:
      - "1555:1433"